### ISSUE TITLE
Add documentation notes for ABI-only fields

### ISSUE THREAD

**Issue by gadomski** [stac-extensions/goes#1]
`goes:image-type`, `goes:mesoscale-image-number`, and maybe `goes:mode` are ABI-specific attributes. The documentation should include a note in the description that they should not be populated if `instrument` != ABI.

**Comment by m-mohr** [comment]
Thanks, I can update it accordingly. Although, as I'm also using goes-glm as prefix, we could also say goes-abi should be the prefix for these fields then (which would not be implemented yet in the goes package).

**Comment by gadomski** [comment]
> we could also say goes-abi should be the prefix for these fields then (which would not be implemented yet in the goes package).

This also makes sense to me. Sub-extensions? `goes:abi:mode`? :-D

**Comment by m-mohr** [comment]
Haha, no, I think I'd simply document them all here but use three different prefixes: goes, goes-abi and goes-glm. Or we use goes for all of them and just specify the scope in the docs. I have no preference, up to you :-)

**Comment by gadomski** [comment]
No major preference either, I think I slightly prefer everything under a `goes:` prefix w/ documentation calling out when they should be used, but happy with whatever.

**Comment by m-mohr** [comment]
Okay, let's do the single prefix and then I'll also add the GLM specific fields here.

So three sections: Common fields, ABI-specific fields, GLM-specific fields. Will Update this week and also update goes-glm accordingly.

**Comment by m-mohr** [comment]
@gadomski Would you mind switching the fields you used for ABI to snake case as it is usually done in STAC? It feels weird so switch between snake case and kebab case in the same extension.

**Comment by m-mohr** [comment]
Fields have been split.

**Comment by gadomski** [comment]
For now, I've created an issue to track: https://github.com/stactools-packages/goes/issues/31. I haven't touched the ABI code in over a year and it looks pretty old, so there will be some additional work required to bring it up to modern best practices. I think leaving it documented for now is ok, as I expect to come back to GOES ABI datasets probably in early 2023 (not currently working them).
