### ISSUE TITLE
goes:mode = 6?

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/goes#3]
It looks like there is a goes:mode 6, which is not documented here.

https://www.ospo.noaa.gov/Operations/GOES/east/g16meso.html
http://localhost:8080/external/planetarycomputer.microsoft.com/api/stac/v1/collections/goes-cmi

**Comment by m-mohr** [comment]
Do you have details about it, @gadomski ?

**Comment by pjhartzell** [comment]
I think this is just a typo in one part of the extension docs. There is no mode 5. The description for "mode 5" is actually mode 6. 

In this section...

>goes:mode
>
>The following values are allowed:
>
>    3: Mode 3 - Consists of one observation of the full disk scene of the earth, three observations of the continental United States (CONUS) scene, and thirty observations for each of two distinct mesoscale scenes every fifteen minutes, during nominal operations.
    4: Mode 4 - Consists of the observation of the full disk scene every five minutes.
    5: Mode 5 - Consists of one observation of the full disk scene of the earth, two observations of the continental United States (CONUS) scene, and twenty observations for each of two distinct mesoscale scenes every ten minutes, during nominal operations.

...change "5: Mode 5" to "6: Mode 6".

The modes look correct in the rest of the extension documentation, the schema, and in the planetary computer [collection](https://planetarycomputer.microsoft.com/api/stac/v1/collections/goes-cmi).

Mode info I looked at: https://www.goes-r.gov/spacesegment/abi.html

**Comment by m-mohr** [comment]
Thanks, good catch. I fixed it.
